/**
 * Languages marked `official` or `de_facto_official` for at least one
 * territory in Unicode CLDR 48 supplemental territory data. Script variants
 * are collapsed to their base language because this list is only a set of
 * suggestions; the metadata combobox accepts any custom BCP 47 value.
 *
 * Source: https://github.com/unicode-org/cldr/blob/release-48/common/supplemental/supplementalData.xml
 */
export const documentLanguages = [
  {code: "sq", name: "Albanian"},
  {code: "am", name: "Amharic"},
  {code: "ar", name: "Arabic"},
  {code: "hy", name: "Armenian"},
  {code: "ay", name: "Aymara"},
  {code: "az", name: "Azerbaijani"},
  {code: "bn", name: "Bangla"},
  {code: "be", name: "Belarusian"},
  {code: "bi", name: "Bislama"},
  {code: "bs", name: "Bosnian"},
  {code: "bg", name: "Bulgarian"},
  {code: "my", name: "Burmese"},
  {code: "yue", name: "Cantonese"},
  {code: "ca", name: "Catalan"},
  {code: "tzm", name: "Central Atlas Tamazight"},
  {code: "ch", name: "Chamorro"},
  {code: "zh", name: "Chinese"},
  {code: "hr", name: "Croatian"},
  {code: "cs", name: "Czech"},
  {code: "da", name: "Danish"},
  {code: "dv", name: "Divehi"},
  {code: "nl", name: "Dutch"},
  {code: "dz", name: "Dzongkha"},
  {code: "en", name: "English"},
  {code: "et", name: "Estonian"},
  {code: "fo", name: "Faroese"},
  {code: "hif", name: "Fiji Hindi"},
  {code: "fj", name: "Fijian"},
  {code: "fil", name: "Filipino"},
  {code: "fi", name: "Finnish"},
  {code: "fr", name: "French"},
  {code: "ka", name: "Georgian"},
  {code: "de", name: "German"},
  {code: "gil", name: "Gilbertese"},
  {code: "el", name: "Greek"},
  {code: "gn", name: "Guarani"},
  {code: "ht", name: "Haitian Creole"},
  {code: "hak", name: "Hakka Chinese"},
  {code: "he", name: "Hebrew"},
  {code: "hi", name: "Hindi"},
  {code: "ho", name: "Hiri Motu"},
  {code: "hu", name: "Hungarian"},
  {code: "is", name: "Icelandic"},
  {code: "id", name: "Indonesian"},
  {code: "ga", name: "Irish"},
  {code: "it", name: "Italian"},
  {code: "ja", name: "Japanese"},
  {code: "kl", name: "Kalaallisut"},
  {code: "kk", name: "Kazakh"},
  {code: "km", name: "Khmer"},
  {code: "rw", name: "Kinyarwanda"},
  {code: "ko", name: "Korean"},
  {code: "ky", name: "Kyrgyz"},
  {code: "lo", name: "Lao"},
  {code: "lv", name: "Latvian"},
  {code: "lt", name: "Lithuanian"},
  {code: "lb", name: "Luxembourgish"},
  {code: "mk", name: "Macedonian"},
  {code: "mg", name: "Malagasy"},
  {code: "ms", name: "Malay"},
  {code: "mt", name: "Maltese"},
  {code: "gv", name: "Manx"},
  {code: "mi", name: "Māori"},
  {code: "mh", name: "Marshallese"},
  {code: "nan", name: "Min Nan Chinese"},
  {code: "mn", name: "Mongolian"},
  {code: "na", name: "Nauru"},
  {code: "ne", name: "Nepali"},
  {code: "niu", name: "Niuean"},
  {code: "nd", name: "North Ndebele"},
  {code: "no", name: "Norwegian"},
  {code: "nb", name: "Norwegian Bokmål"},
  {code: "nn", name: "Norwegian Nynorsk"},
  {code: "ny", name: "Nyanja"},
  {code: "pau", name: "Palauan"},
  {code: "pap", name: "Papiamento"},
  {code: "ps", name: "Pashto"},
  {code: "fa", name: "Persian"},
  {code: "pl", name: "Polish"},
  {code: "pt", name: "Portuguese"},
  {code: "qu", name: "Quechua"},
  {code: "ro", name: "Romanian"},
  {code: "rn", name: "Rundi"},
  {code: "ru", name: "Russian"},
  {code: "sm", name: "Samoan"},
  {code: "sg", name: "Sango"},
  {code: "sr", name: "Serbian"},
  {code: "sn", name: "Shona"},
  {code: "si", name: "Sinhala"},
  {code: "sk", name: "Slovak"},
  {code: "sl", name: "Slovenian"},
  {code: "so", name: "Somali"},
  {code: "st", name: "Southern Sotho"},
  {code: "es", name: "Spanish"},
  {code: "sw", name: "Swahili"},
  {code: "ss", name: "Swati"},
  {code: "sv", name: "Swedish"},
  {code: "gsw", name: "Swiss German"},
  {code: "ty", name: "Tahitian"},
  {code: "tg", name: "Tajik"},
  {code: "ta", name: "Tamil"},
  {code: "tet", name: "Tetum"},
  {code: "th", name: "Thai"},
  {code: "ti", name: "Tigrinya"},
  {code: "tpi", name: "Tok Pisin"},
  {code: "tkl", name: "Tokelau"},
  {code: "to", name: "Tongan"},
  {code: "tn", name: "Tswana"},
  {code: "tr", name: "Turkish"},
  {code: "tk", name: "Turkmen"},
  {code: "tvl", name: "Tuvalu"},
  {code: "uk", name: "Ukrainian"},
  {code: "ur", name: "Urdu"},
  {code: "uz", name: "Uzbek"},
  {code: "vi", name: "Vietnamese"},
  {code: "wni", name: "Ndzwani Comorian"},
  {code: "wo", name: "Wolof"},
  {code: "yo", name: "Yoruba"},
  {code: "zdj", name: "Ngazidja Comorian"},
] as const
