name: Build & Deploy Core

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      deploy_hook: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}
    steps:
      - name: Trigger deploy
        run: curl -X POST $deploy_hook